### ISSUE TITLE
initial deploy fails due to webpack missing

### ISSUE THREAD

**Issue by iturgeon** [rails-lambda/lamby-cookiecutter#17]
Hi, I'm new to lamby and trying to test it out by running through the setup tasks on a pure cookiecutter project.

I was able to run bootstrap, and setup, however deploy fails 

```
› ./bin/deploy
WARN[0000] The "AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CI" variable is not set. Defaulting to a blank string. 
== Lamby build ==
== Cleaning dev dependencies for local deploy. Run ./bin/setup again afterward! ==
== Bundle For Deployment ==
Writing lockfile to /var/task/Gemfile.lock
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this
machine.
== Environments & Configuration ==
== Asset Hosts & Precompiling ==
Compiling...
Compilation failed:
yarn run v1.22.17
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


error Command "webpack" not found.
```

Looking into the _build script, this sort of makes sense to me due to the script clearing out the node_modules directory here. https://github.com/customink/lamby-cookiecutter/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/bin/_build#L5-L8 

Perhaps I missed a step?

**Comment by metaskills** [comment]
> Perhaps I missed a step?

Hey @iturgeon thanks so much for opening an issue. I think you did it right. This highlights a process we avoid internally for our projects... the capability to do deploys outside a CI/CD pipeline. Can you confirm that the changes done in https://github.com/customink/lamby-cookiecutter/commit/c7928013c09b02fd79b96364c8b6a8adee8db46e will fix the problem? My thinking is that node modules is cleaned up to keep the deploy package small further down in that same file.

**Comment by iturgeon** [comment]
@metaskills Yea, that makes sense.  My 5 second fix was to run yarn install just after the changes in the link and it was able to build and deploy

I'm continuing to have issues with an out-of-the box build and deploy.  It's deployed but erroring.  It's likely that building on my M1 is a contributing, I just need to chase it down.  I'll continue and check back in.

**Comment by metaskills** [comment]
Thanks, I got some odd "directory not empty" errors when trying. I feel like they hint to some poor behavior with Docker for Mac filesystem sharing.... on top of Docker for Mac's poor speed as well 😭. If you have the option to use GitHub Actions or some Linux based CI/CD, please do and/or let me what else you find out that I can help with. Cheers.
