### ISSUE TITLE
RailsLambda may not have authorization defined.

### ISSUE THREAD

**Issue by lanks** [rails-lambda/lamby-cookiecutter#20]
I am trying to deploy the cookiecutter but cannot figure out how to get past this... I have tried both on my machine and on github actions and I am getting the same error.

Any ideas how to get past this? Cheers

Error: Failed to create changeset for the stack: salesmock-lambda-production, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-east-1:188234749246:stack/salesmock-lambda-production/06df2aa0-46bf-11ed-956c-0a183a2d2989 is in ROLLBACK_COMPLETE state and can not be updated.

**Comment by metaskills** [comment]
Delete the stack and try again. Sometimes there can be an issue preventing a stack from being newly created. When this happens, it is not possible for CloudFormation to push it forward again because technically a ROLLBACK is a delete. Hope that helps.

**Comment by metaskills** [comment]
Lemme know if this had a resolution, closing for now.
