### ISSUE TITLE
./bin/build is missing in the generated folder – The instructions for installing the projects are not working

### ISSUE THREAD

**Issue by richardsondx** [rails-lambda/lamby-cookiecutter#22]
Straight OOTB the project created didn't have a `./bin/build` folder

```

➜  serverless_apps docker run \
  --rm \
  --interactive \
  --volume "${PWD}:/var/task" \
  ghcr.io/customink/lamby-cookiecutter \
  "gh:customink/lamby-cookiecutter"
Unable to find image 'ghcr.io/customink/lamby-cookiecutter:latest' locally
latest: Pulling from customink/lamby-cookiecutter
ca7dd9ec2225: Pull complete
9e124a36b9ab: Pull complete
edb4d319ce97: Pull complete
b8a071d6393e: Pull complete
91013de9d1f4: Pull complete
5cc7fe4bd869: Pull complete
6e7bde8dcf2d: Pull complete
Digest: sha256:3e3eefeada9fa214bed2e09ef79237ea427e35ca959cd00dc528c2a319e3e5f7
Status: Downloaded newer image for ghcr.io/customink/lamby-cookiecutter:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
project_name [my_awesome_lambda]: project_lambda

➜  serverless_apps cd project_lambda

➜  project_lambda ./bin/build
zsh: no such file or directory: ./bin/build

➜  project_lambda cd bin/
➜  bin ls
deploy rails  rake   setup  test
```

**Comment by richardsondx** [comment]
Looks like it was removed: https://github.com/customink/lamby-cookiecutter/pull/21/files#diff-509badb794a3c29eb034ea3e3fe7ae1724d8861d8bb166273010baa551c02b71

**Comment by metaskills** [comment]
Correct. Everything is in bin/deploy now. I think you might have a cached version. Can you check your home director for a hidden cookiecutter dir/cache?

**Comment by richardsondx** [comment]
I don't see a cache dir but in my home directory there is the following folder: `.cookiecutters/lamby-cookiecutter`

```
 lamby-cookiecutter git:(master) ls -a
.                             .gitignore                    bin                           hooks
..                            CODE_OF_CONDUCT.md            cc-in-docker                  inserts
.git                          Dockerfile                    cookiecutter.json             lambify
.github                       README.md                     docker-compose.yml            {{cookiecutter.project_name}}
```

I also noticed a `.cookiecutter_replay` directory that contains a `lamby-cookiecutter.json`

```
{
  "cookiecutter": {
    "project_name": "first_lambda",
    "_template": "gh:customink/lamby-cookiecutter",
    "_output_dir": "/Users/richardson/Code/SeverlessApp"
  }
}
```


And here's the directory of the project I generated with lamby-cookiecutter
```
➜  project_lambda ls -a
.              .gitignore     Rakefile       db             template.yaml
..             .ruby-version  app            lib            test
.devcontainer  Dockerfile     bin            log            tmp
.gitattributes Gemfile        config         public         vendor
.github        README.md      config.ru      storage
```

**Comment by metaskills** [comment]
So `.cookiecutters/lamby-cookiecutter` is the cache. Can you delete that and create a new project?

**Comment by richardsondx** [comment]
I deleted  `.cookiecutters/lamby-cookiecutter` but I'm still getting the same outcome with `./bin/build`

What's the expected behaviour? How will I notice that it's not the cache version?

**Comment by metaskills** [comment]
Sorry, let me step back a bit. I assumed there was an error with bin/build missing. What is the error and when is it happening? Are you expecting a bin/build?

**Comment by richardsondx** [comment]
@metaskills thanks for the prompt response. I'm getting the same outcome as stated above.

```
➜  project_lambda ./bin/build
zsh: no such file or directory: ./bin/build
```

**Comment by metaskills** [comment]
There is no bin/build anymore, every thing is in one file. I've yet to update the guides to reflect that.

**Comment by metaskills** [comment]
New docs to back up the new cookiecutter just landed. Checkout the new quick start and how lamby works sections. https://lamby.custominktech.com/

**Comment by richardsondx** [comment]
@metaskills 🔥 this is amazing! Thanks! Merry Christmas!
