### ISSUE TITLE
Quick start results in internal server error

### ISSUE THREAD

**Issue by gehan** [rails-lambda/lamby-cookiecutter#28]
I am running Mac OS 13.

If I do the quick start:

```
docker run \
  --rm \
  --interactive \
  --volume "${PWD}:/var/task" \
  ghcr.io/customink/lamby-cookiecutter \
  "gh:customink/lamby-cookiecutter"
```

and then deploy immediately

```
./bin/deploy
```

Then the resulting lambda has an internal server error. If I read the CloudWatch logs I see this:

```
/usr/local/lib/ruby/3.1.0/bundler/definition.rb:507:in `materialize': Could not find mysql2-0.5.4, debug-1.7.1, webrick-1.7.0, web-console-4.2.0, capybara-3.38.0, selenium-webdriver-4.7.1, webdrivers-5.2.0, irb-1.6.2, reline-0.3.2, bindex-0.8.1, addressable-2.8.1, matrix-0.4.2, nokogiri-1.13.10-x86_64-linux, regexp_parser-2.6.1, xpath-3.2.0, rexml-3.2.5, rubyzip-2.3.2, websocket-1.2.9, nio4r-2.5.8, websocket-driver-0.7.5, io-console-0.6.0, public_suffix-5.0.1, racc-1.6.2, date-3.3.3 in locally installed gems (Bundler::GemNotFound)
```

I'd say I'm doing something wrong but I have used the cookie cutter template and so I haven't actually done anything... or am I missing something?

**Comment by metaskills** [comment]
Did you follow this guide fully? https://lamby.custominktech.com/docs/quick-start

**Comment by metaskills** [comment]
Also, I'm gonna double check things on my end too...

**Comment by metaskills** [comment]
OK, ran thru the latest starter. Everything checks out. That error is odd. Did you deploy locally with a devcontainer or with the GitHub action?

**Comment by gehan** [comment]
Ahhh ok sorry! I didn't do the dev container step - I had wrongly assumed that was just for local development. I didn't realise deployment had to be done from within the dev container. 

Up and running now! Sorry for wasting your time. I can now apply to my project - thanks!!

<img width="996" alt="image" src="https://user-images.githubusercontent.com/238662/211755707-46c9bdbb-1b64-48cf-aee1-639cdfcd2553.png">
