### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by hopewise** [rails-lambda/lamby-cookiecutter#29]
Hello

My rails app is currently running behind nginx, as I use some rules to proxy pass some locations so that they appear within my rails app urls, ex: `myapp.com/forum`  which is proxy passed to discourse EC2 instance.

I can add a separate EC2 instance to use nginx as a proxy to my lambda url and have my rails container runs without nginx, however that will cost me extra ec2 server.

The question is, can I use lamby to point traffic to nginx instead of directly into my rails app in my container?

**Comment by metaskills** [comment]
This question should be on the Lamby repo vs the cookiecutter starter project. That said, adding NGINX in the way you described is not going to be easy or serve you well. Here is what I suggest.

* If you have extra headers needed for your Rack app, perhaps add a Rack middleware in your Rails app that ads them for you. I think Rails even has a config for this too that most folks use in production.rb? 
* If you need a relative URL root, consider using the new `rack_app=` setter to configure this as needed. For example:

```ruby
Lamby.config.rack_app = Rack::Builder.new do
  map '/forum' do
    run Rails.application
  end
end.to_app
```

I should cover this in the advanced configs issue:

* https://github.com/customink/lamby/issues/138

**Comment by hopewise** [comment]
Thank you
