### ISSUE TITLE
Getting GemNotFound errors in Cloudwatch after deploy

### ISSUE THREAD

**Issue by albertski** [rails-lambda/lamby-cookiecutter#42]
I'm getting the following errors in Cloudwatch after deploy and can't get the site to load. 

```
/usr/local/lib/ruby/3.2.0/bundler/definition.rb:524:in `materialize': Could not find web-console-4.2.1, capybara-3.39.2, selenium-webdriver-4.10.0, webdrivers-5.3.1, bindex-0.8.1, addressable-2.8.5, matrix-0.4.2, regexp_parser-2.8.1, xpath-3.2.0, rexml-3.2.6, rubyzip-2.3.2, websocket-1.2.10, nio4r-2.5.9, websocket-driver-0.7.6, bigdecimal-3.1.4, public_suffix-5.0.3, psych-5.1.0, stringio-3.0.8 in locally installed gems (Bundler::GemNotFound)
```

This is my GemFile:
```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails"

gem "importmap-rails"
gem "lamby"
gem 'sqlite3'
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "jbuilder"

group :development, :test do
  gem "webrick"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

group :production do
  gem 'lograge'
end

```

Would you know what could be causing this issue?

**Comment by hungnv-sr** [comment]
Same issue, I managed to fix it by changing the build to use amd since my chip is amd, not arm.
But I encounterd other error after that.

**Comment by jeremiahlukus** [comment]
Probably need to add bundle install in your Dockerfile. 

In bin/deploy it assumes you are running bundle install on whatever system your lambda is running (`arm64` in the default example). It then copies that cache over to the Docker image to reduce the time it takes to spin up a new lambda. So if you and not doing a bundle install on a `arm64` machine (ie you are trying to deploy locally from a mac) then you would need to add bundle install in the Dockerfile itself
