### ISSUE TITLE
Github actions failed to run Deploy

### ISSUE THREAD

**Issue by lanks** [rails-lambda/lamby-cookiecutter#44]
Hi there

I am trying to setup the deployment on github actions using Devcontainers.

I am receiving the error below:
`  Setting DockerBuildArgs: {} for RailsLambda function
  
  Failed building function RailsLambda
  
  
  Build Failed
  
  Error: The command '/bin/sh -c gem install 'aws_lambda_ric'' returned a non-zero code: 1
  
  Error: Dev container exec failed: (exit code: 1)
  Error: Dev container exec failed: (exit code: 1)

Also I was previously receiving errors caused by these lines in the deploy.yml file:
`imageName: ghcr.io/lanks/{% include "_cctmp/dash_name.txt" %}-devcontainer
  cacheFrom: ghcr.io/lanks/{% include "_cctmp/dash_name.txt" %}-devcontainer`

The error I received was:
```
  [2023-12-01T08:55:29.408Z] ERROR: parse error on line 1, column 33: bare " in non-quoted-field
  [2023-12-01T08:55:29.411Z] Service 'app' failed to build : Build failed
  [2023-12-01T08:55:29.466Z] Exit code 1
```

I updated these lines and it worked but I am not sure if I need these lines for the container names?
`imageName: ghcr.io/lanks/sm-devcontainer
  cacheFrom: ghcr.io/lanks/sm-devcontainer`

Appreciate any help if anyone knows how to overcome these? Cheers

**Comment by prcongithub** [comment]
Same error, any update here?

**Comment by jeremiahlukus** [comment]
if you can give me some more info i can help you with this. Do you have a link to an example?
