### ISSUE TITLE
Error message: 'github' is undefined

### ISSUE THREAD

**Issue by Ulthran** [rails-lambda/lamby-cookiecutter#48]
Opening an issue on this because I haven't been able to find any reference to it. Also brought up in PR #47.

When running the first command of the quickstart guide, I run into this error because of [this line](https://github.com/rails-lambda/lamby-cookiecutter/blob/c492b0a06a46aef0012f1d0a3596a302b272fc70/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/ci.yml#L99) in the template.

```
$ docker run   --rm   --interactive   --volume "${PWD}:/var/task"   ghcr.io/rails-lambda/lamby-cookiecutter   "gh:rails-lambda/lamby-cookiecutter"

project_name [my_awesome_lambda]:
Unable to create file '.github/workflows/ci.yml'
Error message: 'github' is undefined
Context: {
    "cookiecutter": {
        "_output_dir": "/var/task",
        "_template": "gh:rails-lambda/lamby-cookiecutter",
        "project_name": "my_awesome_lambda"
    }
}
```

I don't understand how anyone using this template doesn't run into this error. Any help is appreciated.

**Comment by ollietreend** [comment]
Hey @Ulthran – I'm experiencing the exact same problem, so you're not alone!

**Comment by Ulthran** [comment]
The fix in #47 worked for me FYI. However, then there have been a bunch more problems I've run into that I'm working on PRs for.

**Comment by jeremiahlukus** [comment]
@Ulthran merged, Ill work on fixing the rest of the errors if more pop up. I usually use[ jumpstart pro](https://jumpstartrails.com/) for new projects so i really only run this command to test things. 


Maybe ill create something like 
https://railsbytes.com/public/templates 

To run a command on a fresh rails app and convert it to use Lamby after i am finished fixing the cookie cutter command

**Comment by jeremiahlukus** [comment]
<img width="716" alt="Screenshot 2024-10-14 at 4 59 39 PM" src="https://github.com/user-attachments/assets/05fcfaed-ecff-4ed3-8c02-9c193aeac966">

Fixed

**Comment by Ulthran** [comment]
Awesome thanks @jeremiahlukus! That's good to know about.

I have some fixes for further issues I've found with the cookiecutter template I could open a PR for if you think it would be helpful? It's not a complete PR yet for sure.

**Comment by jeremiahlukus** [comment]
For sure, feel free to open a PR . Can you open a new issue with the problems you are facing first?
