### ISSUE TITLE
Typo in Gemfile: "aws-skd-ssm" ?

### ISSUE THREAD

**Issue by morimorihoge** [rails-lambda/lamby-cookiecutter#8]
I'm just trying Lamby tutorial but `./bin/setup` failed.

```
$ ./bin/setup
Creating lamby_sample_lamby-sample_run ... done
== Installing dependencies ==
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.............         
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'aws-skd-ssm x86_64-linux' in any of the gem sources listed in your Gemfile.
```

Is `aws-skd-ssm` a typo for `aws-sdk-ssm` ?

https://github.com/customink/lamby-cookiecutter/blob/d3e89f7ea10bac5c9ab18699ee44a4170195c6b5/lambify/Gemfile#L6

I try to fix it and re-run `./bin/setup` then bundler has run succeeded.

**Comment by metaskills** [comment]
It is, let me fix that.

**Comment by metaskills** [comment]
Thanks for letting me know. I just pushed a fix to the cookiecutter.
